### ISSUE TITLE
eh-mfc, how to connect PS5

### ISSUE THREAD

**Issue by zhai1987** [ehmotion/eh-mfc#1]
Dude, I need to buy something, make MFC. Is there a tutorial?

**Comment by ehmotion** [comment]
no tutorial, but you need to know your way around Linux and building simple Makefile-based user apps.
for native telemetry you need to check the clients folder. for extrapolated telemetry based on force feedback from the steering wheel, you need to use the right steering wheel and the proxy adapter and extractor app.

**Comment by ehmotion** [comment]
see here https://github.com/ehmotion/eh-mfc/wiki
